project_id = "vlfmetfruygtdxgpaxkj"

[functions.smartthings-sync]
verify_jwt = false

[functions.smartthings-control]
verify_jwt = false

[functions.generate-notifications]
verify_jwt = false

[functions.smartthings-webhook]
verify_jwt = false

[functions.smartthings-auth-start]
verify_jwt = false

[functions.smartthings-auth-callback]
verify_jwt = false

[functions.tapo-login]
verify_jwt = false
